---
- name: Show Drives on the Desktop
  osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: true
    state: present
  notify:
    - Restart Finder

- name: Show External Drives on the Desktop
  osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: true
    state: present
  notify:
    - Restart Finder

- name: Show Removable Media on the Desktop
  osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: true
    state: present
  notify:
    - Restart Finder

- name: Show Hidden Files
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
    state: present
  notify:
    - Restart Finder

- name: Show File Extensions
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
    state: present
  notify:
    - Restart Finder

- name: Show the Status Bar in Finder
  osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
    state: present
  notify:
    - Restart Finder

- name: Show the Path Bar in Finder
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
    state: present
  notify:
    - Restart Finder

- name: Disable automatic capitalization as it’s annoying when typing code
  become: true
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: false
    state: present

- name: Disable smart dashes as they’re annoying when typing code
  become: true
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: Disable automatic period substitution as it’s annoying when typing code
  become: true
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: Disable smart quotes as they’re annoying when typing code
  become: true
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: Disable auto-correct
  become: true
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
    state: present

# This stops the graphical python window from popping up a message all the time if it crashed
- name: Disable close windows when quitting an app
  become: true
  osx_defaults:
    domain: NSGlobalDomain
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: false
    state: present
