---
- name: Check developer mode
  command: DevToolsSecurity -status
  register: DevToolsSecurity_status
  become: yes

- name: Activate developer mode
  command: DevToolsSecurity -enable
  register: DevToolsSecurity_activation
  when: '"Developer mode is currently disabled" in DevToolsSecurity_status.stdout'
  become: yes
