---
- name: enable developer mode
  include_task: enable-developer-mode.yml

- name: setup desktop defaults that make sense for developers (increase clarity and awareness)
  include_task: defaults-for-dev-clarity.yml
